Created basic options page
kabir-plod/spoiler-blocker pull request #22
Opened 2016-12-12 13:48 UTC by kabir-plod

The page can be viewed at `chrome://extensions`.

2016-12-12 15:06 UTC, varung97 requested changes
I think the default preferences aren't getting saved to the storage. I tried changing default case sensitivity to true, but when I opened the options page again, it was back to false.

2016-12-12 15:11 UTC, varung97 commented on src/options/options.js
> +					label="Overlay/remove" // TODO: clearer label
Should we change the label to `Overlay/Remove`?

2016-12-12 15:41 UTC, kabirgh commented on src/options/options.js
> +					label="Overlay/remove" // TODO: clearer label
I wanted to change this to something more descriptive, actually. Just copied this short form from the options menu of the card as a placeholder.

2016-12-12 16:42 UTC, kabir-plod commented
The new commits should fix the problem. I had forgotten to sync the prefs to chrome storage haha.

2016-12-13 04:05 UTC, varung97 commented
Nice, works perfectly 👍

2016-12-13 04:05 UTC, merged